name = "02-spritesheets"

# Tarmac is able to generate a list of all assets used by the project for
# consumption by other tools.
asset-list-path = "assets.lua"

[[inputs]]
glob = "pack-these/**/*.png"
base-path = "pack-these"

# Set packable to true to tell Tarmac that we're okay with these images being
# packed into spritesheets.
packable = true

codegen = true
codegen-path = "pack-these/init.lua"

[[inputs]]
glob = "dont-pack-these/**/*.png"

# packable defaults to false, but we can also explicitly specify it.
packable = false

codegen = true