name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  call-clabot-workflow:
    uses: Roblox/cla-signature-bot/.github/workflows/clabot-workflow.yml@master
    with:
      whitelist: "LPGhatguy,ZoteTheMighty,cliffchapmanrbx,MagiMaster,MisterUncloaked,amatosov-rbx,dependabot[bot]"
      use-remote-repo: true
      remote-repo-name: "roblox/cla-bot-store"
    secrets: inherit
